### PR TITLE
Dependencies update. Clippy polish.

### PR DESCRIPTION
**Pull request by npatsakula**
Hello there!

I've made some efforts to keep `gbdt-rs` up to date. Any feedback is welcome!

## Motivation

- `time` 0.1 is really outdated.
-  Modern `clippy` detects a lot of non-critical warnings in `gbdt-rs`.
- One of the doc-tests is broken.

## Plan

- [x] Update dependencies: `rand`, `cfg-if`.
- [x] Remove extra dependency: replace `time` by `std` (output LGTM).
- [x] Pass all tests.

### CODE REVIEW

**Comment by dingelish** [comment]
Thanks for the contribution!

**Comment by dingelish** [comment]
@npatsakula do you need us cargo publish it?

**Comment by npatsakula** [comment]
@dingelish that would be nice of you!

**Comment by dingelish** [comment]
cargo publish is done. Thanks again!

**Pull request merged**
